package org.madbit.hibernate.entity;

// Generated 14 mars 2013 22:01:57 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer companyId;
	private String name;
	private Set<Agency> agencies = new HashSet<Agency>(0);

	public Company() {
	}

	public Company(String name) {
		this.name = name;
	}

	public Company(String name, Set<Agency> agencies) {
		this.name = name;
		this.agencies = agencies;
	}

	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Agency> getAgencies() {
		return this.agencies;
	}

	public void setAgencies(Set<Agency> agencies) {
		this.agencies = agencies;
	}

}
