package org.madbit.hibernate.entity;

// Generated 14 mars 2013 22:01:57 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer userId;
	private String login;
	private String password;
	private String fullname;
	
	private Set<Agency> agencies = new HashSet<Agency>(0);

	public User() {
	}

	public User(String login, String password, String fullname) {
		this.login = login;
		this.password = password;
		this.fullname = fullname;
	}

	public User(String login, String password, String fullname,
			Set<Agency> agencies) {
		this.login = login;
		this.password = password;
		this.fullname = fullname;
	
		this.agencies = agencies;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

		public Set<Agency> getAgencies() {
		return this.agencies;
	}

	public void setAgencies(Set<Agency> agencies) {
		this.agencies = agencies;
	}

}
