package com.glg.model.entity;

// Generated 26 déc. 2013 11:40:42 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.sql.Blob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Local generated by hbm2java
 */
@Entity
@Table(name = "LOCAL")
public class Local implements java.io.Serializable {

	private long idLocal;
	private Utilisateur utilisateur;
	private Long codeType;
	private String identifiant;
	private String adresse;
	private String batiment;
	private String escalier;
	private Short etage;
	private String noPorte;
	private String ville;
	private int codePostal;
	private short codePays;
	private Integer surface;
	private Short numPiece;
	private Blob description;
	private Blob assurance;
	private Short codeTypeLocation;
	private String dureeMin;
	private BigDecimal loyer;
	private BigDecimal charge;
	private Long codeConsEnergie;
	private Long codeConsGaz;
	private BigDecimal taxHabitation;
	private BigDecimal taxeFonciere;
	private BigDecimal prixAcquisition;

	public Local() {
	}

	public Local(long idLocal, String identifiant, String ville,
			int codePostal, short codePays) {
		this.idLocal = idLocal;
		this.identifiant = identifiant;
		this.ville = ville;
		this.codePostal = codePostal;
		this.codePays = codePays;
	}

	public Local(long idLocal, Utilisateur utilisateur, Long codeType,
			String identifiant, String adresse, String batiment,
			String escalier, Short etage, String noPorte, String ville,
			int codePostal, short codePays, Integer surface, Short numPiece,
			Blob description, Blob assurance, Short codeTypeLocation,
			String dureeMin, BigDecimal loyer, BigDecimal charge,
			Long codeConsEnergie, Long codeConsGaz, BigDecimal taxHabitation,
			BigDecimal taxeFonciere, BigDecimal prixAcquisition) {
		this.idLocal = idLocal;
		this.utilisateur = utilisateur;
		this.codeType = codeType;
		this.identifiant = identifiant;
		this.adresse = adresse;
		this.batiment = batiment;
		this.escalier = escalier;
		this.etage = etage;
		this.noPorte = noPorte;
		this.ville = ville;
		this.codePostal = codePostal;
		this.codePays = codePays;
		this.surface = surface;
		this.numPiece = numPiece;
		this.description = description;
		this.assurance = assurance;
		this.codeTypeLocation = codeTypeLocation;
		this.dureeMin = dureeMin;
		this.loyer = loyer;
		this.charge = charge;
		this.codeConsEnergie = codeConsEnergie;
		this.codeConsGaz = codeConsGaz;
		this.taxHabitation = taxHabitation;
		this.taxeFonciere = taxeFonciere;
		this.prixAcquisition = prixAcquisition;
	}

	@Id
	@Column(name = "ID_LOCAL", unique = true, nullable = false, precision = 12, scale = 0)
	public long getIdLocal() {
		return this.idLocal;
	}

	public void setIdLocal(long idLocal) {
		this.idLocal = idLocal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USER")
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "CODE_TYPE", precision = 12, scale = 0)
	public Long getCodeType() {
		return this.codeType;
	}

	public void setCodeType(Long codeType) {
		this.codeType = codeType;
	}

	@Column(name = "IDENTIFIANT", nullable = false, length = 80)
	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	@Column(name = "ADRESSE", length = 184)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "BATIMENT", length = 80)
	public String getBatiment() {
		return this.batiment;
	}

	public void setBatiment(String batiment) {
		this.batiment = batiment;
	}

	@Column(name = "ESCALIER", length = 80)
	public String getEscalier() {
		return this.escalier;
	}

	public void setEscalier(String escalier) {
		this.escalier = escalier;
	}

	@Column(name = "ETAGE", precision = 4, scale = 0)
	public Short getEtage() {
		return this.etage;
	}

	public void setEtage(Short etage) {
		this.etage = etage;
	}

	@Column(name = "NO_PORTE", length = 16)
	public String getNoPorte() {
		return this.noPorte;
	}

	public void setNoPorte(String noPorte) {
		this.noPorte = noPorte;
	}

	@Column(name = "VILLE", nullable = false, length = 120)
	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	@Column(name = "CODE_POSTAL", nullable = false, precision = 6, scale = 0)
	public int getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(int codePostal) {
		this.codePostal = codePostal;
	}

	@Column(name = "CODE_PAYS", nullable = false, precision = 4, scale = 0)
	public short getCodePays() {
		return this.codePays;
	}

	public void setCodePays(short codePays) {
		this.codePays = codePays;
	}

	@Column(name = "SURFACE", precision = 6, scale = 0)
	public Integer getSurface() {
		return this.surface;
	}

	public void setSurface(Integer surface) {
		this.surface = surface;
	}

	@Column(name = "NUM_PIECE", precision = 4, scale = 0)
	public Short getNumPiece() {
		return this.numPiece;
	}

	public void setNumPiece(Short numPiece) {
		this.numPiece = numPiece;
	}

	@Column(name = "DESCRIPTION")
	public Blob getDescription() {
		return this.description;
	}

	public void setDescription(Blob description) {
		this.description = description;
	}

	@Column(name = "ASSURANCE")
	public Blob getAssurance() {
		return this.assurance;
	}

	public void setAssurance(Blob assurance) {
		this.assurance = assurance;
	}

	@Column(name = "CODE_TYPE_LOCATION", precision = 3, scale = 0)
	public Short getCodeTypeLocation() {
		return this.codeTypeLocation;
	}

	public void setCodeTypeLocation(Short codeTypeLocation) {
		this.codeTypeLocation = codeTypeLocation;
	}

	@Column(name = "DUREE_MIN", length = 80)
	public String getDureeMin() {
		return this.dureeMin;
	}

	public void setDureeMin(String dureeMin) {
		this.dureeMin = dureeMin;
	}

	@Column(name = "LOYER", precision = 8)
	public BigDecimal getLoyer() {
		return this.loyer;
	}

	public void setLoyer(BigDecimal loyer) {
		this.loyer = loyer;
	}

	@Column(name = "CHARGE", precision = 12)
	public BigDecimal getCharge() {
		return this.charge;
	}

	public void setCharge(BigDecimal charge) {
		this.charge = charge;
	}

	@Column(name = "CODE_CONS_ENERGIE", precision = 12, scale = 0)
	public Long getCodeConsEnergie() {
		return this.codeConsEnergie;
	}

	public void setCodeConsEnergie(Long codeConsEnergie) {
		this.codeConsEnergie = codeConsEnergie;
	}

	@Column(name = "CODE_CONS_GAZ", precision = 12, scale = 0)
	public Long getCodeConsGaz() {
		return this.codeConsGaz;
	}

	public void setCodeConsGaz(Long codeConsGaz) {
		this.codeConsGaz = codeConsGaz;
	}

	@Column(name = "TAX_HABITATION", precision = 12)
	public BigDecimal getTaxHabitation() {
		return this.taxHabitation;
	}

	public void setTaxHabitation(BigDecimal taxHabitation) {
		this.taxHabitation = taxHabitation;
	}

	@Column(name = "TAXE_FONCIERE", precision = 12)
	public BigDecimal getTaxeFonciere() {
		return this.taxeFonciere;
	}

	public void setTaxeFonciere(BigDecimal taxeFonciere) {
		this.taxeFonciere = taxeFonciere;
	}

	@Column(name = "PRIX_ACQUISITION", precision = 12, scale = 3)
	public BigDecimal getPrixAcquisition() {
		return this.prixAcquisition;
	}

	public void setPrixAcquisition(BigDecimal prixAcquisition) {
		this.prixAcquisition = prixAcquisition;
	}

}
