package com.glg.model.entity;

// Generated 26 déc. 2013 11:40:42 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Locataire generated by hbm2java
 */
@Entity
@Table(name = "LOCATAIRE", uniqueConstraints = @UniqueConstraint(columnNames = "EMAIL"))
public class Locataire implements java.io.Serializable {

	private long idLocataire;
	private Utilisateur utilisateur;
	private BigDecimal codeLocataire;
	private String typeLocatire;
	private Date dateCreate;
	private Date dateModify;
	private Date dateDelete;
	private String email;
	private String tel;
	private String telMob;
	private String fax;
	private Blob infoComplet;
	private Blob infoGanarant;
	private Set<Societe> societes = new HashSet<Societe>(0);
	private Set<Particulier> particuliers = new HashSet<Particulier>(0);

	public Locataire() {
	}

	public Locataire(long idLocataire) {
		this.idLocataire = idLocataire;
	}

	public Locataire(long idLocataire, Utilisateur utilisateur,
			BigDecimal codeLocataire, String typeLocatire, Date dateCreate,
			Date dateModify, Date dateDelete, String email, String tel,
			String telMob, String fax, Blob infoComplet, Blob infoGanarant,
			Set<Societe> societes, Set<Particulier> particuliers) {
		this.idLocataire = idLocataire;
		this.utilisateur = utilisateur;
		this.codeLocataire = codeLocataire;
		this.typeLocatire = typeLocatire;
		this.dateCreate = dateCreate;
		this.dateModify = dateModify;
		this.dateDelete = dateDelete;
		this.email = email;
		this.tel = tel;
		this.telMob = telMob;
		this.fax = fax;
		this.infoComplet = infoComplet;
		this.infoGanarant = infoGanarant;
		this.societes = societes;
		this.particuliers = particuliers;
	}

	@Id
	@Column(name = "ID_LOCATAIRE", unique = true, nullable = false, precision = 12, scale = 0)
	public long getIdLocataire() {
		return this.idLocataire;
	}

	public void setIdLocataire(long idLocataire) {
		this.idLocataire = idLocataire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USER")
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "CODE_LOCATAIRE", precision = 22, scale = 0)
	public BigDecimal getCodeLocataire() {
		return this.codeLocataire;
	}

	public void setCodeLocataire(BigDecimal codeLocataire) {
		this.codeLocataire = codeLocataire;
	}

	@Column(name = "TYPE_LOCATIRE", length = 20)
	public String getTypeLocatire() {
		return this.typeLocatire;
	}

	public void setTypeLocatire(String typeLocatire) {
		this.typeLocatire = typeLocatire;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_CREATE", length = 7)
	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_MODIFY", length = 7)
	public Date getDateModify() {
		return this.dateModify;
	}

	public void setDateModify(Date dateModify) {
		this.dateModify = dateModify;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DELETE", length = 7)
	public Date getDateDelete() {
		return this.dateDelete;
	}

	public void setDateDelete(Date dateDelete) {
		this.dateDelete = dateDelete;
	}

	@Column(name = "EMAIL", unique = true, length = 184)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "TEL", length = 80)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "TEL_MOB", length = 80)
	public String getTelMob() {
		return this.telMob;
	}

	public void setTelMob(String telMob) {
		this.telMob = telMob;
	}

	@Column(name = "FAX", length = 80)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "INFO_COMPLET")
	public Blob getInfoComplet() {
		return this.infoComplet;
	}

	public void setInfoComplet(Blob infoComplet) {
		this.infoComplet = infoComplet;
	}

	@Column(name = "INFO_GANARANT")
	public Blob getInfoGanarant() {
		return this.infoGanarant;
	}

	public void setInfoGanarant(Blob infoGanarant) {
		this.infoGanarant = infoGanarant;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locataire")
	public Set<Societe> getSocietes() {
		return this.societes;
	}

	public void setSocietes(Set<Societe> societes) {
		this.societes = societes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locataire")
	public Set<Particulier> getParticuliers() {
		return this.particuliers;
	}

	public void setParticuliers(Set<Particulier> particuliers) {
		this.particuliers = particuliers;
	}

}
