package com.glg.model.entity;

// Generated 26 déc. 2013 11:40:42 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Particulier generated by hbm2java
 */
@Entity
@Table(name = "PARTICULIER")
public class Particulier implements java.io.Serializable {

	private long idParticulier;
	private Locataire locataire;
	private Byte civilitycode;
	private String nom;
	private String prenom;
	private Date dateNaissance;
	private String lieu;

	public Particulier() {
	}

	public Particulier(long idParticulier, String nom, String prenom) {
		this.idParticulier = idParticulier;
		this.nom = nom;
		this.prenom = prenom;
	}

	public Particulier(long idParticulier, Locataire locataire,
			Byte civilitycode, String nom, String prenom, Date dateNaissance,
			String lieu) {
		this.idParticulier = idParticulier;
		this.locataire = locataire;
		this.civilitycode = civilitycode;
		this.nom = nom;
		this.prenom = prenom;
		this.dateNaissance = dateNaissance;
		this.lieu = lieu;
	}

	@Id
	@Column(name = "ID_PARTICULIER", unique = true, nullable = false, precision = 12, scale = 0)
	public long getIdParticulier() {
		return this.idParticulier;
	}

	public void setIdParticulier(long idParticulier) {
		this.idParticulier = idParticulier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_LOCATAIRE")
	public Locataire getLocataire() {
		return this.locataire;
	}

	public void setLocataire(Locataire locataire) {
		this.locataire = locataire;
	}

	@Column(name = "CIVILITYCODE", precision = 2, scale = 0)
	public Byte getCivilitycode() {
		return this.civilitycode;
	}

	public void setCivilitycode(Byte civilitycode) {
		this.civilitycode = civilitycode;
	}

	@Column(name = "NOM", nullable = false, length = 144)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", nullable = false, length = 140)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_NAISSANCE", length = 7)
	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@Column(name = "LIEU", length = 35)
	public String getLieu() {
		return this.lieu;
	}

	public void setLieu(String lieu) {
		this.lieu = lieu;
	}

}
