package com.glg.model.entity;

// Generated 26 déc. 2013 10:57:05 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name = "TEST")
public class Test implements java.io.Serializable {

	private TestId id;

	public Test() {
	}

	public Test(TestId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idTest", column = @Column(name = "ID_TEST", nullable = false, precision = 12, scale = 0)),
			@AttributeOverride(name = "idTest1", column = @Column(name = "ID_TEST1", length = 0)),
			@AttributeOverride(name = "idTest2", column = @Column(name = "ID_TEST2", precision = 22, scale = 0)),
			@AttributeOverride(name = "idTest3", column = @Column(name = "ID_TEST3", precision = 22, scale = 0)) })
	public TestId getId() {
		return this.id;
	}

	public void setId(TestId id) {
		this.id = id;
	}

}
