package com.glg.model.entity;

// Generated 26 déc. 2013 11:40:42 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "UTILISATEUR", uniqueConstraints = @UniqueConstraint(columnNames = {
		"EMAIL", "LOGIN" }))
public class Utilisateur implements java.io.Serializable {

	private long idUser;
	private String login;
	private String password;
	private String confirmpassword;
	private String isuserconnected;
	private Short profilinuseid;
	private String validuser;
	private String lastname;
	private String firstname;
	private Date datecreate;
	private Date datemodify;
	private Date datedelete;
	private String email;
	private Set<Local> locals = new HashSet<Local>(0);
	private Set<Locataire> locataires = new HashSet<Locataire>(0);

	public Utilisateur() {
	}

	public Utilisateur(long idUser, String login, String password,
			String confirmpassword, String validuser, String lastname,
			String firstname, String email) {
		this.idUser = idUser;
		this.login = login;
		this.password = password;
		this.confirmpassword = confirmpassword;
		this.validuser = validuser;
		this.lastname = lastname;
		this.firstname = firstname;
		this.email = email;
	}

	public Utilisateur(long idUser, String login, String password,
			String confirmpassword, String isuserconnected,
			Short profilinuseid, String validuser, String lastname,
			String firstname, Date datecreate, Date datemodify,
			Date datedelete, String email, Set<Local> locals,
			Set<Locataire> locataires) {
		this.idUser = idUser;
		this.login = login;
		this.password = password;
		this.confirmpassword = confirmpassword;
		this.isuserconnected = isuserconnected;
		this.profilinuseid = profilinuseid;
		this.validuser = validuser;
		this.lastname = lastname;
		this.firstname = firstname;
		this.datecreate = datecreate;
		this.datemodify = datemodify;
		this.datedelete = datedelete;
		this.email = email;
		this.locals = locals;
		this.locataires = locataires;
	}

	@Id
	@Column(name = "ID_USER", unique = true, nullable = false, precision = 12, scale = 0)
	public long getIdUser() {
		return this.idUser;
	}

	public void setIdUser(long idUser) {
		this.idUser = idUser;
	}

	@Column(name = "LOGIN", nullable = false, length = 80)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "PASSWORD", nullable = false, length = 80)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "CONFIRMPASSWORD", nullable = false, length = 80)
	public String getConfirmpassword() {
		return this.confirmpassword;
	}

	public void setConfirmpassword(String confirmpassword) {
		this.confirmpassword = confirmpassword;
	}

	@Column(name = "ISUSERCONNECTED", length = 4)
	public String getIsuserconnected() {
		return this.isuserconnected;
	}

	public void setIsuserconnected(String isuserconnected) {
		this.isuserconnected = isuserconnected;
	}

	@Column(name = "PROFILINUSEID", precision = 4, scale = 0)
	public Short getProfilinuseid() {
		return this.profilinuseid;
	}

	public void setProfilinuseid(Short profilinuseid) {
		this.profilinuseid = profilinuseid;
	}

	@Column(name = "VALIDUSER", nullable = false, length = 4)
	public String getValiduser() {
		return this.validuser;
	}

	public void setValiduser(String validuser) {
		this.validuser = validuser;
	}

	@Column(name = "LASTNAME", nullable = false, length = 128)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "FIRSTNAME", nullable = false, length = 128)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATECREATE", length = 7)
	public Date getDatecreate() {
		return this.datecreate;
	}

	public void setDatecreate(Date datecreate) {
		this.datecreate = datecreate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEMODIFY", length = 7)
	public Date getDatemodify() {
		return this.datemodify;
	}

	public void setDatemodify(Date datemodify) {
		this.datemodify = datemodify;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEDELETE", length = 7)
	public Date getDatedelete() {
		return this.datedelete;
	}

	public void setDatedelete(Date datedelete) {
		this.datedelete = datedelete;
	}

	@Column(name = "EMAIL", nullable = false, length = 256)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<Local> getLocals() {
		return this.locals;
	}

	public void setLocals(Set<Local> locals) {
		this.locals = locals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<Locataire> getLocataires() {
		return this.locataires;
	}

	public void setLocataires(Set<Locataire> locataires) {
		this.locataires = locataires;
	}

}
